apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
data:
thanos.yaml: |
'{{ (printf "type: s3\nconfig:\n\tbucket: %s\n\tendpoint: %s\n\tinsecure: true\n\taccess_key: %s\n\tsecret_key: %s" 
  "(lookup "objectbucket.io/v1alpha1" "ObjectBucket" "" "obc-openshift-storage-obc-observability").spec.endpoint.bucketName" 
  "(lookup "objectbucket.io/v1alpha1" "ObjectBucket" "" "obc-openshift-storage-obc-observability").spec.endpoint.bucketHost" 
  "(fromSecret "openshift-storage" "noobaa-admin" "AWS_ACCESS_KEY_ID")" 
  "(fromSecret "openshift-storage" "noobaa-admin" "AWS_SECRET_ACCESS_KEY")" | base64enc | indent 2 }}'
---
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 10Gi

