apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: sysctl-tcp-tuning-all
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=A custom OpenShift tuning parameters for tcp buffers
      include=openshift-control-plane
      [sysctl]
      net.core.rmem_max=16777216
      net.core.wmem_max=16777216
      net.ipv4.tcp_rmem="4096 87380 16777216"
      net.ipv4.tcp_wmem="4096 16384 16777216"
    name: sysctl-tcp-tuning-all
  recommend:
  - match:
    - label: "node-role.kubernetes.io/worker"
    - label: "node-role.kubernetes.io/infra"
    - label: "node-role.kubernetes.io/master"

    priority: 10
    profile: sysctl-tcp-tuning-all

