apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-core-generator
placementBindingDefaults:
  name: core-config-binding 
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  complianceType: "mustonlyhave"
  metadataComplianceType: "musthave"
  severity: medium
  policySets:
    - openshift-plus-hub-core
policies:

- name: policy-acm
  manifests:
    - path: input-acm-observability/


policySets:
  - description: Golcuk clusterında uygulanacak policy leri iceren policyset
    name: policyset-golcuk-core
    placement:
      placementName: placement-golcuk

  - description: Hub clusterında uygulanacak policy leri iceren policyset
    name: policyset-hub-core
    placement:
      placementName: placement-hub
